revoke select on lineitem from max_0_pri_role;
alter role max_0_pri_role with resource queue none;
drop user max_0_pri_role;
drop resource queue rq_max;
revoke select on lineitem from medium_0_pri_role;
alter role medium_0_pri_role with resource queue none;
drop user medium_0_pri_role;
revoke select on lineitem from medium_1_pri_role;
alter role medium_1_pri_role with resource queue none;
drop user medium_1_pri_role;
revoke select on lineitem from medium_2_pri_role;
alter role medium_2_pri_role with resource queue none;
drop user medium_2_pri_role;
revoke select on lineitem from medium_3_pri_role;
alter role medium_3_pri_role with resource queue none;
drop user medium_3_pri_role;
drop resource queue rq_medium;
