revoke select on lineitem from high_0_pri_role;
alter role high_0_pri_role with resource queue none;
drop user high_0_pri_role;
drop resource queue rq_high;
revoke select on lineitem from low_0_pri_role;
alter role low_0_pri_role with resource queue none;
drop user low_0_pri_role;
revoke select on lineitem from low_1_pri_role;
alter role low_1_pri_role with resource queue none;
drop user low_1_pri_role;
revoke select on lineitem from low_2_pri_role;
alter role low_2_pri_role with resource queue none;
drop user low_2_pri_role;
revoke select on lineitem from low_3_pri_role;
alter role low_3_pri_role with resource queue none;
drop user low_3_pri_role;
drop resource queue rq_low;
